spring.datasource.url=jdbc:postgresql://user-service-db:5432/${DB_NAME_DOCKER}
spring.datasource.username=${DB_USERNAME_DOCKER}
spring.datasource.password=${DB_PASSWORD_DOCKER}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=postgresql
spring.data.redis.host=user-service-redis
spring.data.redis.port=6379